# VA2EPR-TNC Manual
# Copyright 2012, 2013 Thomas Cort <va2epr@rac.ca>
#
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.3
# or any later version published by the Free Software Foundation;
# with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
# Texts.  A copy of the license is included in the section entitled "GNU
# Free Documentation License".

va2epr-tnc.pdf: va2epr-tnc.texi
	texi2pdf va2epr-tnc.texi

clean:
	rm -f va2epr-tnc.aux va2epr-tnc.cp va2epr-tnc.cps va2epr-tnc.fn va2epr-tnc.ky va2epr-tnc.log va2epr-tnc.pdf va2epr-tnc.pg va2epr-tnc.toc va2epr-tnc.tp va2epr-tnc.vr
